#! /bin/bash

projectName=$1
syntax=$2

file_dir=.projectMakerFiles

mkdir -p $projectName/src

# syntaxVersion=""
# compiler=""

if [ $syntax == "cpp" ]; then
	# compiler="g++"
	# syntaxVersion="-std=c++20"
	$file_dir/c.sh "$projectName" "g++"
elif [ $syntax == "c" ]; then
	# compiler="gcc"
	# syntaxVersion="-std=c99"
	$file_dir/c.sh "$projectName" "gcc"

elif [ $syntax == "py" ]; then
	$file_dir/py.sh "$projectName" "$syntax"
	echo "todo py"

elif [ $syntax == "php" ]; then
	$file_dir/php.sh "$projectName"
	echo "todo php improvements"

elif [ $syntax == "py-web" ]; then
	$file_dir/py.sh "$projectName" "$syntax"
	echo "todo py-web"

else
	echo "Syntax not supported"
	exit 1
fi




code ./$projectName
